name: send-issue-email

on:
  issues:
    types: [ opened ]

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Comment thank you
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.actor }}, Danke fÃ¼r deine Anfrage! Wir versuchen uns schnellstmÃ¶glich bei dir zu melden â±. Behalte bitte deine Inbox im Auge, da wir dich bei RÃ¼ckfragen in diesem Thread markieren. ğŸ“¯ğŸ“¬